services:
  - type: web
    name: erp-multitenant-backend
    env: docker
    dockerfilePath: infra/Dockerfile.backend
    dockerContext: .
    region: oregon
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET_PROD
        generateWith: true
      - key: ALLOWED_ORIGINS
        sync: false
      - key: COOKIE_SAME_SITE
        value: None
