spring:
  application:
    name: erp-multitenant-backend
  profiles:
    active: dev

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

jwt:
  header: Authorization
  prefix: "Bearer "
  issuer: gestao-estopa-api
  audience: gestao-estopa-web

